spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  jpa:
    hibernate:
      ddl-auto: validate # 운영 환경에서는 테이블 구조가 맞는지 검증만
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

aws:
  s3:
    bucket: ${S3_BUCKET}

sns:
  jwt:
    access-key: ${JWT_ACCESS_KEY}
    refresh-key: ${JWT_REFRESH_KEY}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}  # 운영용 AWS 키 변수 추가
      secret-key: ${AWS_SECRET_KEY}  # 운영용 AWS 키 변수 추가
    region:
      static: ${AWS_REGION}
    s3:
      bucket: ${S3_BUCKET}